export const ADMIN_SIGNIN_REQ = "ADMIN_SIGNIN_REQ"
export const ADMIN_SIGNIN_SUCCESS = "ADMIN_SIGNIN_SUCCESS"
export const ADMIN_SIGNIN_FAIL = "ADMIN_SIGNIN_FAIL"

export const ADMIN_GOOGLE_SIGNIN_REQ = "ADMIN_GOOGLE_SIGNIN_REQ"
export const ADMIN_GOOGLE_SIGNIN_SUCCESS = "ADMIN_GOOGLE_SIGNIN_SUCCESS"
export const ADMIN_GOOGLE_SIGNUP_SUCCESS = "ADMIN_GOOGLE_SIGNUP_SUCCESS"
export const ADMIN_GOOGLE_SIGNIN_FAIL = "ADMIN_GOOGLE_SIGNIN_FAIL"

export const ADMIN_SIGNUP_REQ = "ADMIN_SIGNUP_REQ"
export const ADMIN_SIGNUP_SUCCESS = "ADMIN_SIGNUP_SUCCESS"
export const ADMIN_SIGNUP_FAIL = "ADMIN_SIGNUP_FAIL"

export const ADMIN_LOGOUT_REQ = "ADMIN_LOGOUT_REQ"
export const ADMIN_LOGOUT_SUCCESS = "ADMIN_LOGOUT_SUCCESS"
export const ADMIN_LOGOUT_FAIL = "ADMIN_LOGOUT_FAIL"

export const ADMIN_FORGET_PASSWORD_REQ = "ADMIN_FORGET_PASSWORD_REQ"
export const ADMIN_FORGET_PASSWORD_SUCCESS = "ADMIN_FORGET_PASSWORD_SUCCESS"
export const ADMIN_FORGET_PASSWORD_FAIL = "ADMIN_FORGET_PASSWORD_FAIL"

export const ADMIN_RESET_PASSWORD_REQ = "ADMIN_RESET_PASSWORD_REQ"
export const ADMIN_RESET_PASSWORD_SUCCESS = "ADMIN_RESET_PASSWORD_SUCCESS"
export const ADMIN_RESET_PASSWORD_FAIL = "ADMIN_RESET_PASSWORD_FAIL"


//MIDDLEWARE
export const LOGGED_OUT_MIDDLEWARE_REQ = "LOGGED_OUT_MIDDLEWARE_REQ"
export const LOGGED_OUT_MIDDLEWARE_SUCCESS = "LOGGED_OUT_MIDDLEWARE_SUCCESS"
export const LOGGED_OUT_MIDDLEWARE_FAIL = "LOGGED_OUT_MIDDLEWARE_FAIL"

export const LOGGED_IN_MIDDLEWARE_REQ = "LOGGED_IN_MIDDLEWARE_REQ"
export const LOGGED_IN_MIDDLEWARE_SUCCESS = "LOGGED_IN_MIDDLEWARE_SUCCESS"
export const LOGGED_IN_MIDDLEWARE_FAIL = "LOGGED_IN_MIDDLEWARE_FAIL"


export const UPDATE_ADMIN_REQ = "UPDATE_ADMIN_REQ"
export const UPDATE_ADMIN_SUCCESS = "UPDATE_ADMIN_SUCCESS"
export const UPDATE_ADMIN_FAIL = "UPDATE_ADMIN_FAIL"

export const UPDATE_ADMIN_ACCOUNT_DETAILS_REQ = "UPDATE_ADMIN_ACCOUNT_DETAILS_REQ"
export const UPDATE_ADMIN_ACCOUNT_DETAILS_SUCCESS = "UPDATE_ADMIN_ACCOUNT_DETAILS_SUCCESS"
export const UPDATE_ADMIN_ACCOUNT_DETAILS_FAIL = "UPDATE_ADMIN_ACCOUNT_DETAILS_FAIL"