export const GET_ALL_ADVERTISEMENT_REQ = "GET_ALL_ADVERTISEMENT_REQ"
export const GET_ALL_ADVERTISEMENT_SUCCESS = "GET_ALL_ADVERTISEMENT_SUCCESS"
export const GET_ALL_ADVERTISEMENT_FAIL = "GET_ALL_ADVERTISEMENT_FAIL"
