export const CREATE_APPOINTMENT_REQ = "CREATE_APPOINTMENT_REQ"
export const CREATE_APPOINTMENT_SUCCESS = "CREATE_APPOINTMENT_SUCCESS"
export const CREATE_APPOINTMENT_FAIL = "CREATE_APPOINTMENT_FAIl"

export const DELETE_APPOINTMENT_REQ = "DELETE_APPOINTMENT_REQ"
export const DELETE_APPOINTMENT_SUCCESS = "DELETE_APPOINTMENT_SUCCESS"
export const DELETE_APPOINTMENT_FAIL = "DELETE_APPOINTMENT_FAIl"

export const EDIT_APPOINTMENT_REQ = "EDIT_APPOINTMENT_REQ"
export const EDIT_APPOINTMENT_SUCCESS = "EDIT_APPOINTMENT_SUCCESS"
export const EDIT_APPOINTMENT_FAIL = "EDIT_APPOINTMENT_FAIl"