export const GET_BARBERLIST_REQ = "GET_BARBERLIST_REQ"
export const GET_BARBERLIST_SUCCESS = "GET_BARBERLIST_SUCCESS"
export const GET_BARBERLIST_FAIL = "GET_BARBERLIST_FAIL"

export const CREATE_BARBER_REQ = "CREATE_BARBER_REQ"
export const CREATE_BARBER_SUCCESS = "CREATE_BARBER_SUCCESS"
export const CREATE_BARBER_FAIL = "CREATE_BARBER_FAIl"

export const UPDATE_BARBER_REQ = "UPDATE_BARBER_REQ"
export const UPDATE_BARBER_SUCCESS = "UPDATE_BARBER_SUCCESS"
export const UPDATE_BARBER_FAIL = "UPDATE_BARBER_FAIl"

export const GET_BARBER_SERVICES_REQ = "GET_BARBER_SERVICES_REQ"
export const GET_BARBER_SERVICES_SUCCESS = "GET_BARBER_SERVICES_SUCCESS"
export const GET_BARBER_SERVICES_FAIL = "GET_BARBER_SERVICES_FAIL"

export const GETALLBARBERS_BYSERVICEID_REQ = "GETALLBARBERS_BYSERVICEID_REQ"
export const GETALLBARBERS_BYSERVICEID_SUCCESS = "GETALLBARBERS_BYSERVICEID_SUCCESS"
export const GETALLBARBERS_BYSERVICEID_FAIL = "GETALLBARBERS_BYSERVICEID_FAIL"

export const BARBER_SERVED_QUEUE_REQ = "BARBER_SERVED_QUEUE_REQ"
export const BARBER_SERVED_QUEUE_SUCCESS = "BARBER_SERVED_QUEUE_SUCCESS"
export const BARBER_SERVED_QUEUE_FAIL = "BARBER_SERVED_QUEUE_FAIL"

export const DELETE_BARBER_REQ = "DELETE_BARBER_REQ"
export const DELETE_BARBER_SUCCESS = "DELETE_BARBER_SUCCESS"
export const DELETE_BARBER_FAIL = "DELETE_BARBER_FAIL"

export const APPROVE_BARBER_REQ = "APPROVE_BARBER_REQ"
export const APPROVE_BARBER_SUCCESS = "APPROVE_BARBER_SUCCESS"
export const APPROVE_BARBER_FAIL = "APPROVE_BARBER_FAIL"