export const GET_BARBERLIST_REQ = "GET_BARBERLIST_REQ"
export const GET_BARBERLIST_SUCCESS = "GET_BARBERLIST_SUCCESS"
export const GET_BARBERLIST_FAIL = "GET_BARBERLIST_FAIL"

export const CREATE_BARBER_REQ = "CREATE_BARBER_REQ"
export const CREATE_BARBER_SUCCESS = "CREATE_BARBER_SUCCESS"
export const CREATE_BARBER_FAIL = "CREATE_BARBER_FAIl"

export const UPDATE_BARBER_REQ = "UPDATE_BARBER_REQ"
export const UPDATE_BARBER_SUCCESS = "UPDATE_BARBER_SUCCESS"
export const UPDATE_BARBER_FAIL = "UPDATE_BARBER_FAIl"