export const BARBER_SIGNIN_REQ = "BARBER_SIGNIN_REQ"
export const BARBER_SIGNIN_SUCCESS = "BARBER_SIGNIN_SUCCESS"
export const BARBER_SIGNIN_FAIL = "BARBER_SIGNIN_FAIL"

export const BARBER_GOOGLE_SIGNIN_REQ = "BARBER_GOOGLE_SIGNIN_REQ"
export const BARBER_GOOGLE_SIGNIN_SUCCESS = "BARBER_GOOGLE_SIGNIN_SUCCESS"
export const BARBER_GOOGLE_SIGNUP_SUCCESS = "BARBER_GOOGLE_SIGNUP_SUCCESS"
export const BARBER_GOOGLE_SIGNIN_FAIL = "BARBER_GOOGLE_SIGNIN_FAIL"

export const BARBER_SIGNUP_REQ = "BARBER_SIGNUP_REQ"
export const BARBER_SIGNUP_SUCCESS = "BARBER_SIGNUP_SUCCESS"
export const BARBER_SIGNUP_FAIL = "BARBER_SIGNUP_FAIL"

export const BARBER_LOGOUT_REQ = "BARBER_LOGOUT_REQ"
export const BARBER_LOGOUT_SUCCESS = "BARBER_LOGOUT_SUCCESS"
export const BARBER_LOGOUT_FAIL = "BARBER_LOGOUT_FAIL"

export const BARBER_FORGET_PASSWORD_REQ = "BARBER_FORGET_PASSWORD_REQ"
export const BARBER_FORGET_PASSWORD_SUCCESS = "BARBER_FORGET_PASSWORD_SUCCESS"
export const BARBER_FORGET_PASSWORD_FAIL = "BARBER_FORGET_PASSWORD_FAIL"

export const BARBER_RESET_PASSWORD_REQ = "BARBER_RESET_PASSWORD_REQ"
export const BARBER_RESET_PASSWORD_SUCCESS = "BARBER_RESET_PASSWORD_SUCCESS"
export const BARBER_RESET_PASSWORD_FAIL = "BARBER_RESET_PASSWORD_FAIL"


//MIDDLEWARE
export const LOGGED_OUT_MIDDLEWARE_REQ = "LOGGED_OUT_MIDDLEWARE_REQ"
export const LOGGED_OUT_MIDDLEWARE_SUCCESS = "LOGGED_OUT_MIDDLEWARE_SUCCESS"
export const LOGGED_OUT_MIDDLEWARE_FAIL = "LOGGED_OUT_MIDDLEWARE_FAIL"

export const LOGGED_IN_MIDDLEWARE_REQ = "LOGGED_IN_MIDDLEWARE_REQ"
export const LOGGED_IN_MIDDLEWARE_SUCCESS = "LOGGED_IN_MIDDLEWARE_SUCCESS"
export const LOGGED_IN_MIDDLEWARE_FAIL = "LOGGED_IN_MIDDLEWARE_FAIL"

export const BARBER_ONLINE_STATUS_REQ = "BARBER_ONLINE_STATUS_REQ"
export const BARBER_ONLINE_STATUS_SUCCESS = "BARBER_ONLINE_STATUS_SUCCESS"
export const BARBER_ONLINE_STATUS_FAIL = "BARBER_ONLINE_STATUS_FAIL"


export const UPDATE_BARBER_REQ = "UPDATE_BARBER_REQ"
export const UPDATE_BARBER_SUCCESS = "UPDATE_BARBER_SUCCESS"
export const UPDATE_BARBER_FAIL = "UPDATE_BARBER_FAIL"

export const UPDATE_BARBER_ACCOUNT_DETAILS_REQ = "UPDATE_BARBER_ACCOUNT_DETAILS_REQ"
export const UPDATE_BARBER_ACCOUNT_DETAILS_SUCCESS = "UPDATE_BARBER_ACCOUNT_DETAILS_SUCCESS"
export const UPDATE_BARBER_ACCOUNT_DETAILS_FAIL = "UPDATE_BARBER_ACCOUNT_DETAILS_FAIL"


export const BARBER_QUELIST_REQ = "BARBER_QUELIST_REQ"
export const BARBER_QUELIST_SUCCESS = "BARBER_QUELIST_SUCCESS"
export const BARBER_QUELIST_FAIL = "BARBER_QUELIST_FAIL"

export const BARBER_SERVED_QUE_REQ = "BARBER_SERVED_QUE_REQ"
export const BARBER_SERVED_QUE_SUCCESS = "BARBER_SERVED_QUE_SUCCESS"
export const BARBER_SERVED_QUE_FAIL = "BARBER_SERVED_QUE_FAIL"

export const BARBER_ACCOUNT_DETAILS_REQ = "BARBER_ACCOUNT_DETAILS_REQ"
export const BARBER_ACCOUNT_DETAILS_SUCCESS = "BARBER_ACCOUNT_DETAILS_SUCCESS"
export const BARBER_ACCOUNT_DETAILS_FAIL = "BARBER_ACCOUNT_DETAILS_FAIL"

export const BARBER_VERIFY_EMAIL_REQ = "BARBER_VERIFY_EMAIL_REQ"
export const BARBER_VERIFY_EMAIL_SUCCESS = "BARBER_VERIFY_EMAIL_SUCCESS"
export const BARBER_VERIFY_EMAIL_FAIL = "BARBER_VERIFY_EMAIL_FAIL"

export const BARBER_VERIFIED_STATUS_REQ = "BARBER_VERIFIED_STATUS_REQ"
export const BARBER_VERIFIED_STATUS_SUCCESS = "BARBER_VERIFIED_STATUS_SUCCESS"
export const BARBER_VERIFIED_STATUS_FAIL = "BARBER_VERIFIED_STATUS_FAIL"