export const GET_ALL_COUNTRIES_REQ = "GET_ALL_COUNTRIES_REQ"
export const GET_ALL_COUNTRIES_SUCCESS = "GET_ALL_COUNTRIES_SUCCESS"
export const GET_ALL_COUNTRIES_FAIL = "GET_ALL_COUNTRIES_FAIL"

export const GET_ALL_CITIES_REQ = "GET_ALL_CITIES_REQ"
export const GET_ALL_CITIES_SUCCESS = "GET_ALL_CITIES_SUCCESS"
export const GET_ALL_CITIES_FAIL = "GET_ALL_CITIES_FAIL"

export const GET_ALL_TIMEZONES_REQ = "GET_ALL_TIMEZONES_REQ"
export const GET_ALL_TIMEZONES_SUCCESS = "GET_ALL_TIMEZONE_SUCCESS"
export const GET_ALL_TIMEZONE_FAIL = "GET_ALL_TIMEZONE_FAIL"