export const SINGLE_JOINQUEUE_REQ = "SINGLE_JOINQUEUE_REQ"
export const SINGLE_JOINQUEUE_SUCCESS = "SINGLE_JOINQUEUE_SUCCESS"
export const SINGLE_JOINQUEUE_FAIL = "SINGLE_JOINQUEUE_FAIL"

export const QUELIST_REQ = "QUELIST_REQ"
export const QUELIST_SUCCESS = "QUELIST_SUCCESS"
export const QUELIST_FAIL = "QUELIST_FAIL"

export const AUTOJOIN_REQ = "AUTOJOIN_REQ"
export const AUTOJOIN_SUCCESS = "AUTOJOIN_SUCCESS"
export const AUTOJOIN_FAIL = "AUTOJOIN_FAIL"

export const GROUP_BARBER_SERVICE_JOIN_SUCCESS = "GROUP_BARBER_SERVICE_JOIN_SUCCESS"