export const SINGLE_JOINQUEUE_REQ = "SINGLE_JOINQUEUE_REQ"
export const SINGLE_JOINQUEUE_SUCCESS = "SINGLE_JOINQUEUE_SUCCESS"
export const SINGLE_JOINQUEUE_FAIL = "SINGLE_JOINQUEUE_FAIL"

export const QUELIST_REQ = "QUELIST_REQ"
export const QUELIST_SUCCESS = "QUELIST_SUCCESS"
export const QUELIST_FAIL = "QUELIST_FAIL"

export const AUTOJOIN_REQ = "AUTOJOIN_REQ"
export const AUTOJOIN_SUCCESS = "AUTOJOIN_SUCCESS"
export const AUTOJOIN_FAIL = "AUTOJOIN_FAIL"

export const GROUP_JOIN_REQ = "GROUP_JOIN_REQ"
export const GROUP_JOIN_SUCCESS = "GROUP_JOIN_SUCCESS"
export const GROUP_JOIN_FAIL = "GROUP_JOIN_FAIL"

export const CANCEL_QUEUE_REQ = "CANCEL_QUEUE_REQ"
export const CANCEL_QUEUE_SUCCESS = "CANCEL_QUEUE_SUCCESS"
export const CANCEL_QUEUE_FAIL = "CANCEL_QUEUE_FAIL"