export const SINGLE_NOTIFY_BARBER_REQ = "SINGLE_NOTIFY_BARBER_REQ"
export const SINGLE_NOTIFY_BARBER_SUCCESS = "SINGLE_NOTIFY_BARBER_SUCCESS"
export const SINGLE_NOTIFY_BARBER_FAIL = "SINGLE_NOTIFY_BARBER_FAIL"

export const MULTIPLE_NOTIFY_BARBER_REQ = "MULTIPLE_NOTIFY_BARBER_REQ"
export const MULTIPLE_NOTIFY_BARBER_SUCCESS = "MULTIPLE_NOTIFY_BARBER_SUCCESS"
export const MULTIPLE_NOTIFY_BARBER_FAIL = "MULTIPLE_NOTIFY_BARBER_FAIL"

export const GET_ALL_NOTIFY_BARBER_REQ = "GET_ALL_NOTIFY_BARBER_REQ"
export const GET_ALL_NOTIFY_BARBER_SUCCESS = "GET_ALL_NOTIFY_BARBER_SUCCESS"
export const GET_ALL_NOTIFY_BARBER_FAIL = "GET_ALL_NOTIFY_BARBER_FAIL"