export const CREATE_SALON_REQ = "CREATE_SALON_REQ"
export const CREATE_SALON_SUCCESS = "CREATE_SALON_SUCCESS"
export const CREATE_SALON_FAIL = "CREATE_SALON_FAIL"

export const GET_SALONLIST_REQ = "GET_SALONLIST_REQ"
export const GET_SALONLIST_SUCCESS = "GET_SALONLIST_SUCCESS"
export const GET_SALONLIST_FAIL = "GET_SALONLIST_FAIL"

export const UPDATE_SALON_REQ = "UPDATE_SALON_REQ"
export const UPDATE_SALON_SUCCESS = "UPDATE_SALON_SUCCESS"
export const UPDATE_SALON_FAIL = "UPDATE_SALON_FAIL"