export const CREATE_SALON_REQ = "CREATE_SALON_REQ"
export const CREATE_SALON_SUCCESS = "CREATE_SALON_SUCCESS"
export const CREATE_SALON_FAIL = "CREATE_SALON_FAIL"

export const GET_SALONLIST_REQ = "GET_SALONLIST_REQ"
export const GET_SALONLIST_SUCCESS = "GET_SALONLIST_SUCCESS"
export const GET_SALONLIST_FAIL = "GET_SALONLIST_FAIL"

export const UPDATE_SALON_REQ = "UPDATE_SALON_REQ"
export const UPDATE_SALON_SUCCESS = "UPDATE_SALON_SUCCESS"
export const UPDATE_SALON_FAIL = "UPDATE_SALON_FAIL"

export const GET_ALL_SALON_SERVICES_REQ = "GET_ALL_SALON_SERVICES_REQ"
export const GET_ALL_SALON_SERVICES_SUCCESS = "GET_ALL_SALON_SERVICES_SUCCESS"
export const GET_ALL_SALON_SERVICES_FAIL = "GET_ALL_SALON_SERVICES_FAIL"

export const DELETE_SALON_REQ = "DELETE_SALON_REQ"
export const DELETE_SALON_SUCCESS = "DELETE_SALON_SUCCESS"
export const DELETE_SALON_FAIL = "DELETE_SALON_FAIL"

export const CONNECT_BARBER_SALON_REQ = "CONNECT_BARBER_SALON_REQ"
export const CONNECT_BARBER_SALON_SUCCESS = "CONNECT_BARBER_SALON_SUCCESS"
export const CONNECT_BARBER_SALON_FAIL = "CONNECT_BARBER_SALON_FAIL"

export const SALON_SETTINGS_UPDATE_REQ = "SALON_SETTINGS_UPDATE_REQ"
export const SALON_SETTINGS_UPDATE_SUCCESS = "SALON_SETTINGS_UPDATE_SUCCESS"
export const SALON_SETTINGS_UPDATE_FAIL = "SALON_SETTINGS_UPDATE_FAIL"