export const USER_SIGNUP_REQ = "USER_SIGNUP_REQ"
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS"
export const USER_SIGNUP_FAIL = "USER_SIGNUP_FAIL"

export const USER_SIGNIN_REQ = "USER_SIGNIN_REQ"
export const USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS"
export const USER_SIGNIN_FAIL = "USER_SIGNIN_FAIL"
export const USER_SIGNIN_RESET = "USER_SIGNIN_RESET"
export const GOOGLE_SIGNIN_REQ = "GOOGLE_SIGNIN_REQ"

export const USER_LOGOUT_REQ = "USER_LOGOUT_REQ"
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS"
export const USER_LOGOUT_FAIL = "USER_LOGOUT_FAIL"
export const USER_LOGOUT_RESET = "USER_LOGOUT_RESET"